// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRqBtsV1kE8l9kzOkY2_bQD5-NCtWMp4',
    appId: '1:220181745905:web:3fa0077fff662131209950',
    messagingSenderId: '220181745905',
    projectId: 'noteapp-8c815',
    authDomain: 'noteapp-8c815.firebaseapp.com',
    storageBucket: 'noteapp-8c815.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdCD7zbZqz5e5ubIfhuB1USFoGANjwUU',
    appId: '1:220181745905:android:f33d40c640da72d6209950',
    messagingSenderId: '220181745905',
    projectId: 'noteapp-8c815',
    storageBucket: 'noteapp-8c815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiNi5vtQnrVIbVjDpgoG3bopzl34a5Ed0',
    appId: '1:220181745905:ios:c8867580676e5eab209950',
    messagingSenderId: '220181745905',
    projectId: 'noteapp-8c815',
    storageBucket: 'noteapp-8c815.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiNi5vtQnrVIbVjDpgoG3bopzl34a5Ed0',
    appId: '1:220181745905:ios:ffc0a0d312a6a6b4209950',
    messagingSenderId: '220181745905',
    projectId: 'noteapp-8c815',
    storageBucket: 'noteapp-8c815.appspot.com',
    iosBundleId: 'com.example.noteapp.RunnerTests',
  );
}
